{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "namros.fullname" . }}-gateway
  labels:
    {{- include "namros.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
    {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "namros.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.monitoring.podMonitor.path | quote }}
      interval: {{ .Values.monitoring.podMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout | quote }}
{{- end }}
